### ISSUE TITLE
[QUESTION] Android Support

### ISSUE THREAD

**Issue by erwinsonbp** [MyLegGuy/Higurashi-Vita#11]
Hey, you're doing great work here. I just recently took interest on this when I tried searching for Android ports for the Higurashi remakes.
Do you not do builds for Android anymore?
I haven't seen your repo yet but will it be hard if I want to continue your work in the Android builds (in case you won't do them anymore)? I can't check the repo now because I'm on my phone but I'm assuming you must be doing some reverse engineering in the Unity engine files? (which, is a thing I'm not very confident about).
Edit:
I am thinking that the previously released Android build would still work but after many new releases after 1.8, I think it would be great if those changes are merged for the Android build too.
Edit:
Nevermind. There are so many files (and others that looks like not in the repo that are needed like the actual Android Project) to be able to compile it.
Yeah, probably something I cannot do. Lol. Especially the reverse engineering part. I don't know how you put it up, but if it worked, you're amazing. I just hope there's a chance for the Android build to be back up (and updated too).

**Comment by MyLegGuy** [comment]
I deleted the code for touch controls so there's no Android builds anymore for newer versions. Even if you wanted to add touch controls back yourself, compiling is very complicated because Google doesn't encourage C programming for Android.
The day may come when I update the Android version, but that day isn't coming any time soon. 

If you still want to use the older version, the tutorial is on [reddit](https://old.reddit.com/r/Higurashinonakakoroni/comments/6lfvde/release_higurashi_remake_android_port/) still. You'd have to use v1.8 of the engine and v1.6.1 of the HigurashiVitaConverter. The old Android version is kinda bad, but I think it still might be your best option if you want to play on Android.

**Comment by erwinsonbp** [comment]
Thanks! I haven't tried it yet but I'll check what I can do with the old version. I haven't checked how the script converter works so I'm afraid it won't work anymore because the guys at 07th-mod made many changes to the Assembly-CSharp since the time you released your Android build (so there maybe breaking changes (again, I don't know how you convert the scripts and all, so it's just an assumption)).

Still, thanks for your time on making this.

**Comment by MyLegGuy** [comment]
You'd need to use an older version of the PS3 patch, the newer versions changed too much.
The most easy way is to just use the auto-installer program I wrote with the video tutorial for that being here: https://www.youtube.com/watch?v=PKSpGPK3NGA

Alternatively, there's a manual install method. Tutorial from [here](https://wololo.net/talk/viewtopic.php?f=116&t=48223):
MANUAL INSTRUCTIONS
====================
Step 1 - Find your StreamingAssets folder. For me, chapter 2's StreamingAssets folder was at C:\Program Files (x86)\Steam\steamapps\common\Higurashi 02 - Watanagashi\HigurashiEp02_Data\StreamingAssets.
Step 2 - Head [here](https://github.com/MyLegGuy/resources).
Step 3 - Select one of the files you see on the Github page. The file you choose depends on which chapter of the game you are patching. For example, if I was patching chapter 2, Watanagashi, I would open "watanagashi.urls"
Step 4 - After you open the file, you'll see a bunch of URLs. Download all of them by copying and pasting them into your browser's URL bar. There should be 4 in total.
Step 5 - Unzip all of the files you just downloaded.
Step 5.5 - After unzipping the files you downloaded, you should see folders with names like "Update", "SE", "CG", and "CGAlt".
Step 6 - Move these folders into your StreamingAssets folder. If done correctly, you should be asked if you want to overwrite some files. Choose to do so.


--
Either method, you install the PS3 patch before running the script converter.
