### ISSUE TITLE
"If variable ... jump" not working.

### ISSUE THREAD

**Issue by releasethebeans** [MyLegGuy/Higurashi-Vita#12]
In Tsukihime I can't get to the "other" 3 routes that requires a flag check early in the game.

Attached is the problematic script (changed to txt for Github support). Although I'm pretty sure the flagcheck didn't work in any other script.

If I save in the middle of the script I can see that the flags are set properly/adding the "regard" value, but for some reason are not triggering the "IF" script jump.

[s31.txt](https://github.com/MyLegGuy/Higurashi-Vita/files/4011015/s31.txt)

**Comment by MyLegGuy** [comment]
thanks for the report
could you send me your save file so i can test it for myself?
the file is located in the game folder, and it's named "savX" with X being the zero-based save number.

**Comment by releasethebeans** [comment]
Sorry for the late reply, here are 3 different saves from different earlier choices. According to what I've read on the scripts, they all should jump to either s35.scr or s502.scr but none does on my end.
[tsukihime saves.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/4036212/tsukihime.saves.zip)

**Comment by MyLegGuy** [comment]
please try this build when you are free. akiha_regard=1, so you will be brought to s502.scr.
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.3/Higurashi-Vita-beta-v2.9.4.vpk

**Comment by releasethebeans** [comment]
So far so good. Thank you so much for the fix and for making this. Closing.
