### ISSUE TITLE
Episode 1 of higurashi (but not every game) causing crashing.

### ISSUE THREAD

**Issue by Callazy** [MyLegGuy/Higurashi-Vita#14]
Hi there, 

I would just like to let you know that the latest update seems to cause a crash on trying to open the StreamingAssets file of higurashi episode 1 for example. Basically I press the file to open the game and after a few seconds the app crashes.

By reverting to version 2.9.3 solves the issue. Could it be just me? I'm new around here, created an account just for this in fact since I love the app but haven't seen anyone report this.

**Comment by MyLegGuy** [comment]
thank you for the bug report. i'm glad you like my program.

i released a new version and i think it fixed the problem.

**Comment by Callazy** [comment]
Yup, all fixed, thanks!
