### ISSUE TITLE
Poor sprite scaling in Umineko

### ISSUE THREAD

**Issue by retosik** [MyLegGuy/Higurashi-Vita#2]
Higurashi-Vita: https://i.imgur.com/QOMrZ1Q.png
VNDS Interpreter (Android) for comparison (from same source): https://i.imgur.com/oTzGusx.png

**Comment by MyLegGuy** [comment]
Check out [v2.6.1](https://github.com/MyLegGuy/Higurashi-Vita/releases). It should fix this issue.

**Comment by MyLegGuy** [comment]
Oh, I thought you were talking about the one pixel gap between the character and the bottom screen.
Anyway, I definitely fixed it now. Check out [v2.6.2](https://github.com/MyLegGuy/Higurashi-Vita/releases).

**Comment by retosik** [comment]
Cool. But I think the newest version is broken... has empty logo, empty background and crashes on boot.
https://imgur.com/a/ZRwb1pR

**Comment by MyLegGuy** [comment]
Wow, you're quick. That VPK was only up a minute or two after release. Just redownload it.

**Comment by retosik** [comment]
Oh I see.

Looks like it was fixed, graphics look great now. Thanks.
https://i.imgur.com/LNlN7Co.png
