### ISSUE TITLE
RotateBG() function causes current script file to abruptly end.

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#21]
In ch6 Day 2-1 this function is used, which immediately crashes the script file. Hashing out the line with the command causes the script to continue as normal.

**Comment by MyLegGuy** [comment]
I'm pretty sure this function does nothing:
https://github.com/07th-mod/higurashi-assembly/blob/mina-mod/Assets.Scripts.Core.Buriko/BurikoScriptFile.cs#L778
So it's safe to ignore.

**Comment by Theswweet** [comment]
Huh. I decided to double-check on PC - the EnlargeScreen() function right before it did something, sure, but I didn't see any rotation. Seems like you're right, and it does nothing.
