### ISSUE TITLE
SetColorOfMessage() function causes script files to crash in Chapter 6

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#23]
SetColorOfMessage( TRUE, 0xff, 0xbb, 0xff );

Sets color of the font, pretty self-explanatory. Removing the line works - the color just, obviously, doesn't change.

**Comment by Theswweet** [comment]
Worth noting - this function is used *very* liberally in Chapter 6. If you're going to pick and choose which functions to get working, this one would be on my list.

**Comment by MyLegGuy** [comment]
Okay, I've implemented it properly.
New build:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.4.2-BETA-3.vpk

I've also set all the new commands to do nothing.
The game should no longer just crash when it sees one.
These are the new commands that are still unimplemented:
```
DrawFragment
DrawSpriteFixedSize
DrawSpriteWithFilteringFixedSize
FragmentListScreen
FragmentViewChapterScreen
JumpScriptSection
RotateBG
SetWindowBackground
ShiftSection
ShowChapterPreview
ShowChapterScreen
ShowExtras
ShowTips
StopFragment
Update
```
Whenever one of these unimplemented commands executes, its name will be written to ux0:data/HIGURASHI/log.txt and the screen will flash pink briefly.
So if you're playing, seeing pink flashes everywhere, and nothing is working, check log.txt.
Then you can find your location in the script file and make a bug report.
* log.txt is cleared every time you restart the application.
* commands that I was already ignoring will continue to be completely ignored without even the flash. I'm assuming commands that weren't essential before still aren't essential.

HideWindow was set to be the same as DisableWindow.
That's not *exactly* the correct behavior, but it'll work for now. I'll fix it next time. I'm keeping the issue open until then.

RotateBG is currently ignored. I'll investigate it, so I'm leaving that issue open too.

**Comment by Theswweet** [comment]
Thanks again! I reconverted ch6 and updated the vpk, text color is working perfectly!
