### ISSUE TITLE
DrawSpriteFixedSize() function necessary for Chapter 7

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#29]
In the latter portion of Minagoroshi, this function is used for a bunch of pngs that give a bunch of dialog from a specific character. It's important that it gets fixed/implemented. Otherwise, with the current build, it's just a big pink screen for what feels like a minute every time it's called. There's 10 of these images, all used in a similar fashion.

```
//fixed size version forces the sprite to a specific size, regardless of the source image size
	DrawSpriteFixedSize( 11, "Mina1", NULL, 50, -240, 0, 0, 0, 257, 480, 0, FALSE, FALSE, 0, 0, 15, 1000, TRUE );
	//DrawSprite( 1, "Mina1", NULL, 50, -240, 0, 0, 0, 0, FALSE, FALSE, 0, 0, 15, 1000, TRUE );
	Wait( 20000 );
	DisplayWindow();
```

**Comment by MyLegGuy** [comment]
I'm working on it and will probably have it ready later today.

when looking for examples of this command in chapter 8, I found these:
```
_mats_007.txt:  DrawSpriteFixedSize(10, "Si_Ta3a_1", NULL, 151, 246, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 10, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(11, "Si_Ta3a_2", NULL, 151, 278, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 11, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(12, "Si_Ta3a_3", NULL, 151, 307, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 12, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(10, "Si_Ta4a", NULL, 62, 180, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 10, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(11, "Si_Ta4b", NULL, 62, 210, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 11, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(12, "Si_Ta4c", NULL, 62, 240, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 12, 0, TRUE );
_mats_007.txt:  DrawSpriteFixedSize(13, "Si_Ta4d", NULL, 62, 270, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 13, 0, TRUE );
_mats_024.txt:  DrawSpriteFixedSize( 0, "Oko_eyex1", NULL, 90-320, 300-240, 0, 0, 0, 533, 80, 0, FALSE, FALSE, 0, 256-90, 20, 0, TRUE );
_mats_024.txt:  DrawSpriteFixedSize( 1, "Me_eyex1", NULL, 7-320, 100-240, 0, 0, 0, 800, 120, 0, FALSE, FALSE, 0, 256-90, 20, 0, TRUE );
test.txt:       DrawSpriteFixedSize( 11, "Mina1", NULL, 50, -240, 0, 0, 0, 257, 480, 0, FALSE, FALSE, 0, 0, 15, 1000, TRUE );
test.txt:       DrawSpriteFixedSize( 0, "Kei_eyexa2", NULL, -150-320, 100-240, 0, 0, 0, 533, 80, 0, FALSE, FALSE, 0, 256-90, 20, 0, TRUE );
test.txt:       DrawSpriteFixedSize( 1, "Oh_eyexa1", NULL, 277-320, 300-240, 0, 0, 0, 533, 80, 0, FALSE, FALSE, 0, 256-90, 20, 0, TRUE );
test.txt:       DrawSpriteFixedSize( 0, "Sa_eyexa2", NULL, -50-320, 100-240, 0, 0, 0, 533, 80, 0, FALSE, FALSE, 0, 256-90, 20, 0, TRUE );
```
The fourth to last argument is a number 0-256 that determines how transparent the image is.
0 is opaque and 256 is invisible. This rule is reflected in my testing and in your example.
That is why I'm very confused by these examples. Most of them have max alpha, 256. Meaning they show an invisible sprite on screen?
What's the use of that? Are these specific instances weird leftovers, like all uses of RotateBG?
I tried copying & pasting these into a test script using a different image and nothing shows up.
Could you please check one of these out in game to confirm if they do nothing?
(There may be similar instances in the other chapters, but I don't have their scripts to check.)

**Comment by Theswweet** [comment]
I'll keep an eye out for 'em, for sure.

**Comment by MyLegGuy** [comment]
I've implemented it.
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.4.2-BETA-4.vpk

EnlargeScreen has also been implemented. Please test that too when you get the chance. I think it's around the RotateBG command.

**Comment by Theswweet** [comment]
Alright, I found them in _mats_007.txt, and they do show up on PC.

Here's the code for the first set:

```
DrawScene( "black" , 1000 );
	DrawSpriteFixedSize(10, "Si_Ta3a_1", NULL, 151, 246, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 10, 0, TRUE );
	MoveSprite(10, 151, 196, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 2000 );
	DrawSpriteFixedSize(11, "Si_Ta3a_2", NULL, 151, 278, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 11, 0, TRUE );
	MoveSprite(11, 151, 228, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 2000 );
	DrawSpriteFixedSize(12, "Si_Ta3a_3", NULL, 151, 307, 0, 320, 240, 337, 29, 0, FALSE, FALSE, 0, 256, 12, 0, TRUE );
	MoveSprite(12, 151, 257, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 4000 );
	DrawScene( "black" , 3000 );
```

...and here's the picture to go with it. Basically each of the images is a line of text, that pops onto the black scene when you click to continue, from the bottom of the window.

![20200623201201_1](https://user-images.githubusercontent.com/5161970/85495222-f80ff400-b58e-11ea-844a-1e07f69d346f.jpg)

...and the second set of code.
```

DrawScene( "black" , 1000 );
	DrawSpriteFixedSize(10, "Si_Ta4a", NULL, 62, 180, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 10, 0, TRUE );
	MoveSprite(10, 12, 180, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 2000 );
	DrawSpriteFixedSize(11, "Si_Ta4b", NULL, 62, 210, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 11, 0, TRUE );
	MoveSprite(11, 12, 210, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 2000 );
	DrawSpriteFixedSize(12, "Si_Ta4c", NULL, 62, 240, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 12, 0, TRUE );
	MoveSprite(12, 12, 240, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 2000 );
	DrawSpriteFixedSize(13, "Si_Ta4d", NULL, 62, 270, 0, 320, 240, 628, 30, 0, FALSE, FALSE, 0, 256, 13, 0, TRUE );
	MoveSprite(13, 12, 270, 0, 0, 0, 0, 0, 300, TRUE);
	Wait( 4000 );
	DrawScene( "black" , 3000 );
```

Much like the first scene, but the "text" comes from a different direction.
![20200623201725_1](https://user-images.githubusercontent.com/5161970/85495327-255ca200-b58f-11ea-9226-3d100de88e79.jpg)

**Comment by Theswweet** [comment]
Just had the chance to test it in-game on Vita - for whatever reason it's not showing up, but I know the code is mostly right, because briefly, I did see the picture after the long wait() function ended.

Any reason that it might be invisible in Minagoroshi, even without transparency?

On another note, EnlargeBG() seems to work as intended.

**Comment by MyLegGuy** [comment]
that's because i forgot to make it wait for its fadein to finish.

i've fixed this and some more sprite related stuff:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.5-BETA-5b.vpk
please test this and #30

**Comment by Theswweet** [comment]
This is almost there! This is popping up correctly, but there seems to be a missing effect here... apologies for spoilers, it's necessary.

PC:

![20200627162352_1](https://user-images.githubusercontent.com/5161970/85934098-0dd53000-b893-11ea-9c07-4e594d52e4be.jpg)

Vita:

![2020-06-27-160157](https://user-images.githubusercontent.com/5161970/85934099-1594d480-b893-11ea-8d9d-4a2539f7fe0b.png)

**Comment by MyLegGuy** [comment]
The blend between the text image and background?
Can you check the image file to see if the right side is partially transparent?
If it's not, check the image file on the PC version too.

The positioning is clearly wrong. Can you post the DrawSpriteFixedSize command for this part?
This isn't the same one as the code you initially posted because the text is on the left side of the screen this time.
Assuming the transparency effect isn't part of the image, it could also be special usage of DrawSpriteFixedSize.

**Comment by Theswweet** [comment]
Yeah, sorry - this section would be this:

```
DrawSpriteFixedSize( 1, "Mina2", NULL, -307, -240, 0, 0, 0, 257, 480, 0, FALSE, FALSE, 0, 0, 15, 1000, TRUE );
	Wait( 30000 );
	DisplayWindow();
```
As for the image itself, here it is straight from the PC's CG folder:

![mina2](https://user-images.githubusercontent.com/5161970/85936285-05d6b980-b8ae-11ea-841d-3f1c1100b50d.png)

No transparency. It must be an effect.

**Comment by MyLegGuy** [comment]
well that was an [easy](https://github.com/MyLegGuy/Higurashi-Vita/commit/be42285752ca8cb7e101cfd039d20c7d82a8b368) fix.
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.5-BETA-6.vpk

**Comment by Theswweet** [comment]
Yup, tested just for sanity - everything is working as it should!

**Comment by Theswweet** [comment]
Oh, yeah, probably closed this prematurely having not tested ch8's implentation at the time - it works there too!
