### ISSUE TITLE
Crash after "All right, then----" (Fate Stay/Night)

### ISSUE THREAD

**Issue by ordinary-smth** [MyLegGuy/Higurashi-Vita#31]
It's the last line in 'fate07-08.scr' file

The game link: https://mega.nz/file/mksG0CrY#my-Xh23lwGPB6M9UfFveSuJvbMsTDY_pAbA9CE8GzFI

**Comment by MyLegGuy** [comment]
sorry for the late reply, i've been kinda busy.
it would be helpful if you could give be a save file so i can easily test this part. they are located inside the game folder.

**Comment by ordinary-smth** [comment]
Sure, here you go: https://drive.google.com/file/d/1qwrSr5BPCsBlZHS9ZqDBtPfCKnZ_onIE/view?usp=sharing

**Comment by MyLegGuy** [comment]
thank you for the detailed bug report.
this update will likely fix the issue:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.5-BETA-10.vpk

**Comment by ordinary-smth** [comment]
It works flawlessly now, thanks for your help.
