### ISSUE TITLE
VNDS Clone - Kanon

### ISSUE THREAD

**Issue by felixsrg** [MyLegGuy/Higurashi-Vita#32]
So I've recently found the VNDS converter for Kanon, trying it on both DS's and Android's VNDS interpreter, everything seems to be working perfectly, but on Vita, calling **'bgload'** right before **'setimg'** doesn't seem to be able to refresh the foreground sprite, and so the picture looks like they get staked on top.

Additional to this, I've found that after some time into this "staking", the interpreter doesn't load a background or foreground picture anymore and you are left with a blackscreen while the text keeps rolling.

Here's the game link (it's 256x192 version before Vita convertion but the scripts are the same): [MEGA](https://mega.nz/folder/sl4ygIpK#sVHBXVCumZUn_wge8Kqx0A/file/A8BFESAb)

It happens right from the beginning as soon as sprites are loaded, in script: **SEEN0070.scr**

I think it may have to do with how the scripts handle variables or the labels, but any help will be greatly appreciated.

**Comment by MyLegGuy** [comment]
thank you for your detailed bug report and patience. I believe I have fixed it. When you're free, try this vpk: https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0/zHigurashi-Vita-3.0.1-BETA1.vpk

**Comment by felixsrg** [comment]
Thank you very much, the bug has been fixed on the new VPK, sprites now reload perfectly and the scripts for now seem to be loading properly.
