### ISSUE TITLE
Text offset in ADV mode

### ISSUE THREAD

**Issue by joshhuynh98** [MyLegGuy/Higurashi-Vita#33]
I noticed that for some fonts aside from the default (for example in my case Brookerly), characters such as "y", "g" are cut off at the bottom in ADV mode. Is there some way to add a settings that allow for the textbox to be offset from the bottom in ADV mode?

**Comment by milraen** [comment]
I wanted to just verify this comment by stating I have the same issue when I switch to adv mode.  I tested the other vnds.vpks prior to 2.9.4 and they don't have this issue of cutting off the 'y' and 'g' in adv mode.  Something about the coding in 2.9.4 and up seems to offset the text in adv mode.  Hope you can find a fix for this issue.  Great work though.  Thank you for providing it.

**Comment by MyLegGuy** [comment]
thank you guys for the report. when i'm free i will look at it.

**Comment by MyLegGuy** [comment]
well, it's fixed now. sorry i was so lazy.
