### ISSUE TITLE
Red text not appearing red in Umineko?

### ISSUE THREAD

**Issue by SerChido** [MyLegGuy/Higurashi-Vita#40]
I've seen this is supposed to have been added in 2.9.4, but using the latest version it doesn't work. Is this a bug or is it because of the converter? Are there any solutions?

**Comment by MyLegGuy** [comment]
Thank you for the report.
I wasn't clear. I actually added support for colored text the Higurashi games.

But I decided to finally implement VNDS text color.
You can test it with this beta build:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0.2/Higurashi-Vita-v3.0.3-BETA-2.vpk

**Comment by SerChido** [comment]
Thanks for the response! The red text is indeed working in this version. Does it have any major bugs to your knowledge or can I continue playing with it?

**Comment by lochana-Dineko** [comment]
I've messed with it and it looks to be alright. You can probably continue using it without any problems.

**Comment by MyLegGuy** [comment]
I highly doubt it added any new bugs. Go nuts.
