### ISSUE TITLE
Possible bug with custom adv textboxes?

### ISSUE THREAD

**Issue by lochana-Dineko** [MyLegGuy/Higurashi-Vita#42]
![Untitled](https://user-images.githubusercontent.com/30839724/115994184-8f046d00-a5f3-11eb-91d7-5f6a51191b62.png)

I've been using VNDS, and randomly decided to try to set a custom adv textbox. When 'small' textbox is set the image seems to stretch out on the right. This might not be an issue with 16:9 widescreen novels but it shows up here.

I could have messed up somewhere with the _gamespecific.lua commands, but I'm reasonably sure I didn't.

**Comment by lochana-Dineko** [comment]
This seems similar to the white filter issue earlier. Maybe the windows build is outdated? I'll try re compiling.

**Comment by MyLegGuy** [comment]
thank you for your bug report.
please try this new build:
(for windows) https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0.2/Higurashi-Windows-v3.0.3-test2.zip
(for vita) https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0.2/Higurashi-Vita-v3.0.3-BETA-3.vpk

**Comment by lochana-Dineko** [comment]
![Untitled](https://user-images.githubusercontent.com/30839724/116223280-001b6000-a76d-11eb-8501-2786b5e17d88.png)
Yup, it works with the new build. Thanks!
I'll close this issue.
