### ISSUE TITLE
Add support for other language?

### ISSUE THREAD

**Issue by dkrmdi** [MyLegGuy/Higurashi-Vita#43]
Can you add Japanese and Korean fonts? I have scripts in those languages, but VNDS clone cannot display those languages.

I mainly use VN for studying language, and I prefer to read VNs in Japanese. Also I usually like Korean translation better. Korean is more simliar to Japanese so.

**Comment by MyLegGuy** [comment]
Are you sure it doesn't already work?
You're using the latest version, 3.0.2, right?
Both of these worked for me:
```
text Ё Ђ Ѓ Є Ѕ І Ї Ј Љ Њ Ћ Ќ Ў Џ А Б В Г Д Е Ж З И Й К Л М Н О П Р С Т У Ф Х Ц Ч Ш Щ Ъ Ы Ь Э Ю Я а б в г д е ж з и й к л м н о п р с т у
text aあああbああああcあああああdああああああeあああああああf
```

Also, you can override the default font by placing a file called "default.ttf" inside the game folder. Example: `ux0:data/HIGURASHI/Games/somegame/default.ttf`

**Comment by dkrmdi** [comment]
My bad. It's working very well. I'll close this issue. Also thank you for letting me know how to override the default font.
