### ISSUE TITLE
includedpreset.txt not found

### ISSUE THREAD

**Issue by whistleconcert** [MyLegGuy/Higurashi-Vita#47]
when attempting to load kanon and cross-channel, both having gone through the vnds converter, I get an error saying includedpreset.txt not found and that the game folder is invalid

I'm not really sure what this means or how I can fix it.. thank you!

**Comment by MyLegGuy** [comment]
it means that the file at: `ux0:data/HIGURASHi/Games/<whatever-game-folder>/isvnds` does not exist.

i think there are two possibilities here.
1. you accidentally copied the wrong folder to your vita. the vnds converter copies the converted game to another folder called `<game-name>-converted`.
2. you accidentally put the game in a subdirectory. like `ux0:data/HIGURASHi/Games/<whatever-game-folder>/<another folder>/isvnds`

**Comment by whistleconcert** [comment]
> 

It was the second one!! Tested and works. thanks so much for the awesome fix and your super fast response, you are awesome!
