### ISSUE TITLE
Tsukihime hangs on line

### ISSUE THREAD

**Issue by rika09** [MyLegGuy/Higurashi-Vita#5]
Check more info in this thread https://www.reddit.com/r/VitaPiracy/comments/8z403g/tsukihime_vhd_vnds_clone/?st=jlbyt3o8&sh=7077826f is that program or could be game bug?

**Comment by MyLegGuy** [comment]
Sorry for the late reply. Can you supply me with a save file right before it hangs so I can easily debug it? Save files can be found at "ux0:data/HIGURASHI/Games/Tsukihime/sav{X}".

**Comment by MyLegGuy** [comment]
Actually, try this new VPK and tell me if it fixes it:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.8/Higurashi-unstable-v2.8.1.vpk

It's the Higurashi themed one, just for testing.

**Comment by rika09** [comment]
Yes this one works thanks.

**Comment by MyLegGuy** [comment]
Nice. The fix will be in the next version.
