### ISSUE TITLE
Issue with Never7 option variables

### ISSUE THREAD

**Issue by pr0dukt** [MyLegGuy/Higurashi-Vita#9]
In Never7, ported using your latest converter, after using the weeb general VNDS converter from the retail PC version. Managed to get the entire game to work and run fairly smoothly, aside from some audio skips here and there, as I had to use the .ogg files for the script to recognize them. the legArchive file was not being read no matter how many times i compiled it. 

However I got that in workable condition now, whats really irking me is this new issue I've stumbled upon. On the various multi choice response prompts in the game, Regardless of  the selection made by the player, the script pointer always treats the first option on list of choices (usually just two) as true every time. Have not been able to figure out why this is occuring.

Any assistance would be much obliged Leg. =)

**Comment by MyLegGuy** [comment]
Please upload one of the game's script files that includes a choice for me to look at.

**Comment by pr0dukt** [comment]
Sure thing. Had to compress to zip due to file extension being .scr.

Let me know if you find anything. Thanks for taking the time bro.

[hl2d1.scr.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/2708997/hl2d1.scr.zip)

**Comment by MyLegGuy** [comment]
Thanks for the detailed bug report. Try this build: [Higurashi-vpk-zipped.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/2711676/Higurashi-vpk-zipped.zip)

**Comment by pr0dukt** [comment]
Working great now, much obliged for fixing that Leg.
